### ISSUE TITLE
Token & Core functionality ToDo

### ISSUE THREAD

**Issue by Afats** [Afats/composo#1]
- [x] - Test 998 children owning 998 + 1155 children
- [x] - Transfer + test of child ERC-998 tokens
- [x] - Burn 998/1155 tokens
- [x] - Gas prediction cost function 
- [x] - Composable data structure needs to persist on page refresh (using windows.sessionStorage)
- [x] - Mapping of token ID to IPFS data (for both 998 and 1155) on their respective smart contracts (NOT FINISHED FOR ALL)
