### ISSUE TITLE
User Interface ToDo

### ISSUE THREAD

**Issue by Afats** [Afats/composo#2]
- [x] - Update buttons UI and text displayed above button inputs. Add descriptions of what exactly is going to happen in dot points when a user enters in token IDs, etc. once a user clicks on one of the buttons
- [x] - CSS button, position and bg styling
- [x] - Mint child 998 button shouldn’t have an amounts input - can only mint one
- [x] - state variables for descriptions & other metadata as part of metadata schema
- [x] - add shortened owner contract address as part of display metadata
- [x] - Display num of tokens on batch transfer + child 998 functionality completion
- [x] - Improve rendering logic to be contract agnostic but instead favour parent tokens up top regardless
- [x] - Change ownership stage on token transfer for demo
- [x] - render different node colour for root 988, child 998 and 1155 Childs (check if node has parents/children or isERC11551...)
- [x] - edit rendering logic to shift nodes past right-most nodes
