### ISSUE TITLE
Security & Repo ToDo

### ISSUE THREAD

**Issue by Afats** [Afats/composo#3]
- [x] - Hide api token in environment variable
- [ ] - Implement basic Echidna/Etheno smart contract fuzzer functions if there is time (week 9 & 10)
- [x] - Remove unnecessary packages and files
- [x] - Update repo readme
