### ISSUE TITLE
Slides & Demo ToDo

### ISSUE THREAD

**Issue by Afats** [Afats/composo#4]
- [x] - Finish and submit slides by week 8
- [x] - Show Figma hifi prototype
- [x] - Need to explain how the ownership mapping works with diagrams
- [x] - Briefly cover helper functions and transfer functions added to smart contracts (screenshots of function code/call ?)
- [x] - Need to show we use HTTP gateway caching to improve IPFS file retrieval performance to make it usable
- [x] - A comparison of our initial architecture design versus what we ended up doing (very similar, couldn’t implement view provenance because …)
- [x] - Overview of evaluation criteria and what has been evaluated? (Compare cost of storing all data on contract vs IPFS, cost of contract deployment and token transfers, compare current Supply Chain auditing costs vs 998-at-scale costs)
- [x] - Slides for demoing a sub-part that is to be recycled 
- [x] -  Compare goals set out in t2 vs results in t3
- [x] - How the supply chain use-case can be taken further (use of TPCs, zk-Proofs)
- [x] - Additional use cases of 998s (games, DIDs) (even though it's a draft proposal protocol)
